#!/bin/bash

dest_path="/opt/scripts/gitlab/webhook_receiver/"

echo "Installing the gitlab webhook receiver."
rm -r $dest_path
rm /etc/init.d/webhook_receiver
git clone https://gitlab.zeus-coding.de/arlindne/webhook_receiver.git
cd webhook_receiver
mv ubuntu_service/webhook_receiver /etc/init.d/
chmod +x /etc/init.d/webhook_receiver
mkdir -p $dest_path
mv webhook_receiver.rb $dest_path
mv helper $dest_path
mv config $dest_path
sudo update-rc.d webhook_receiver defaults
sudo service webhook_receiver start
cd ..
rm -r webhook_receiver
#shred -u $0;
